# Generated by Django 3.1.3 on 2021-08-01 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210731_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_watchlist', serialize=False, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
