# Generated by Django 3.1.3 on 2021-08-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210801_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='watching',
            field=models.ManyToManyField(to='auctions.Listing'),
        ),
    ]
