# Generated by Django 3.1.3 on 2021-08-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bids_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='won',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
