# Generated by Django 3.1.3 on 2021-08-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210806_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='file_path',
            field=models.ImageField(default='/Users/hafsatusman/Desktop/Independent Study /commerce/media/imgaes/depositphotos_227725020-stock-illustration-image-available-icon-flat-vector.jpeg', upload_to='imgaes/', verbose_name=''),
        ),
    ]
