# Generated by Django 3.1.3 on 2021-08-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210806_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='file_path',
            field=models.ImageField(default='imgaes/default.jpg', upload_to='imgaes/', verbose_name=''),
        ),
    ]
