# Generated by Django 3.1.3 on 2021-08-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210806_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='file_path',
            field=models.ImageField(default='imgaes/default.jpeg', upload_to='imgaes/', verbose_name=''),
        ),
    ]
